name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on perl ${{ matrix.perl_version }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        # noble, bookworm, jammy, bullseye
        # jammy 5.34 is ubuntu-22.04, in coverage run
        perl_version: [ 5.38.2, 5.36.0, 5.34.0, 5.32.1 ]
        experimental: [ false ]
        include:
          - perl_version: 5.40.1
            experimental: true

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup cache (carton)
      uses: actions/cache@v3
      with:
        path: local
        key: ubuntu-22-perl-${{ matrix.perl_version }}-carton-${{ hashFiles('cpanfile.snapshot') }}

    - name: Setup cache (perl)
      id: cache-perl
      uses: actions/cache@v3
      with:
        path: ~/perl5
        key: ubuntu-22-perl-${{ matrix.perl_version }}

    - name: Install correct perl
      if: steps.cache-perl.outputs.cache-hit != 'true'
      run: |
          wget -qO - https://install.perlbrew.pl | bash
          ~/perl5/perlbrew/bin/perlbrew install --notest ${{ matrix.perl_version }}
          ~/perl5/perlbrew/bin/perlbrew clean

    - name: Add packages
      run: |
        sudo apt update
        sudo apt install -y gettext language-pack-en language-pack-de language-pack-sv-base=1:22.04+20220415 language-pack-sv=1:22.04+20220415 libimage-magick-perl
        ~/perl5/perlbrew/bin/perlbrew exec vendor/bin/carton install --deployment
        commonlib/bin/gettext-makemo FixMyStreet

    - name: Run tests
      run: ~/perl5/perlbrew/bin/perlbrew exec script/test --jobs 3 t
